name: Build and Test Workflow

on:
  push:
    branches:
      - devtask/*
  workflow_dispatch:
    inputs:
      release_version:
        description:  Provide the branch/tag to build and test
        required: false

jobs:

  build_test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_version != '' }}

    steps:
    
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{  github.event.inputs.release_version }}

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-enabled: false # Do not checkout internally
          java-version: 11

      - name: Create settings.xml
        run: echo "${{ vars.MAVEN_SETTINGS_XML }}" | base64 -d > settings.xml

      - name: Run tests
        run: mvn test

      - name: Run Build
        run: mvn -B package -DskipTests --file pom.xml

